const productItems = [
  {
    id: 'p1',
    image: 'images/product-1.jpg',
    title: 'PUMA',
    rate: '1200',
    gender: ' Men',
  },

  {
    id: 'p2',
    image: 'images/product-2.jfif',
    title: 'Developer ',
    rate: '450',
    gender: ' Men',
  },
  {
    id: 'p3',
    image: 'src/assets/images/product-3.jfif',
    title: 'Design ',
    rate: '350',
    gender: ' Men',
  },
  {
    id: 'p4',
    image: 'src/assets/images/product-4.jfif',
    title: 'Polo ',
    rate: '550',
    gender: 'Men',
  },
  {
    id: 'p5',
    image: 'src/assets/images/product-5.jfif',
    title: 'Nike ',
    rate: '300',
    gender: 'Men',
  },
  {
    id: 'p6',
    image: 'src/assets/images/product-6.jfif',
    title: 'Printed | Round neck ',
    rate: '400',
    gender: 'Men',
  },
  {
    id: 'p7',
    image: 'src/assets/images/product-7.jfif',
    title: 'Queen | Full sleeve',
    rate: '300',
    gender: 'Women',
  },
  {
    id: 'p8',
    image: 'src/assets/images/product-8.jfif',
    title: 'Design | Theme',
    rate: '700',
    gender: 'Men',
  },
  {
    id: 'p9',
    image: 'src/assets/images/product-9.jfif',
    title: 'Coder ',
    rate: '450',
    gender: 'Men',
  },
  {
    id: 'p10',
    image: 'src/assets/images/product-10.jfif',
    title: 'Printed | Butterfly ',
    rate: '480',
    gender: 'Women',
  },
  {
    id: 'p11',
    image: 'src/assets/images/product-11.jfif',
    title: 'White ',
    rate: '350',
    gender: 'Men',
  },
  {
    id: 'p12',
    image: 'src/assets/images/product-12.jfif',
    title: 'Graphic print  ',
    rate: '300',
    gender: ' Women',
  },

  {
    id: 'p13',
    image: 'src/assets/images/product-13.jfif',
    title: 'Coder ',
    rate: '700',
    gender: ' Men',
  },
  {
    id: 'p14',
    image: 'src/assets/images/product-14.jfif',
    title: 'Printed | Green ',
    rate: '650',
    gender: 'Women',
  },
  {
    id: 'p15',
    image: 'src/assets/images/product-15.jfif',
    title: 'Cat ',
    rate: '400',
    gender: 'Women',
  },
  {
    id: 'p16',
    image: 'src/assets/images/product-16.jfif',
    title: 'Plain white ',
    rate: '450',
    gender: 'Men',
  },
];

export default productItems;
